version: 0.2

phases:
 
  pre_build:
    commands:
      - docker info
      # Authenticate to Amazon ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 688567283850.dkr.ecr.us-east-1.amazonaws.com

  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      # Build the Docker image
      - echo "Building the Docker image..."
      - docker build -t flask-app .
  post_build:
    commands:
      # Tag the Docker image and push it to Amazon ECR
      - echo "Tagging the Docker image..."
      - docker tag flask-app:latest 688567283850.dkr.ecr.us-east-1.amazonaws.com/assignment3-repo:latest
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 688567283850.dkr.ecr.us-east-1.amazonaws.com/assignment3-repo:latest

artifacts:
  files:
    - '**/*'
